
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Banner from '@/Components/Banner'
import Image from 'next/image'
import Card from '@/Components/Card'
import coffeeStoresData from "../data/coffestores.json"
export async function getStaticProps(context) {
  console.log("hi getStaticProps")
  return {
    props: {
      coffestores:coffeeStoresData,
    }, // will be passed to the page component as props
  };
}

export default function Home(props:any) {
  console.log("props", props);


  const handleOnBannerBtnClick=()=>{
    console.log("hi banner button")
  }
  
  return (
    <>
      <Head>
        <title>Coffee Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick}/>
        <div className={styles.heroImage}>
          <Image src="/hero-image.png" width={700} height={400} alt='image'/>
        </div>
      
       
        {props.coffestores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffestores.map((coffestore:any) => {
                return (
                  <Card
                    key={coffestore.id}
                    name={coffestore.name}
                    imgUrl={coffestore.imgUrl}
                    href={`/coffestore/${coffestore.id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
       
      </main>
    </>
  )
}
